exclude: "^.vscode/|^biome.jsonc$|^tsconfig.*.json"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # - repo: local
  #   hooks:
  #     - id: prettier format
  #       name: prettier format
  #       entry: bun x prettier . --write
  #       language: system
  #       pass_filenames: false # This makes it a lot faster

  - repo: local
    hooks:
      - id: biome check
        name: biome check
        entry: bun x biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
